swagger:
  openapi: 3.0.3
  info:
    title: Movie API
    description: API for managing movies.
    version: 1.0.0
  paths:
    /movie:
      post:
        summary: Create a new movie
        description: Creates a new movie entry.
        operationId: createMovie
        requestBody:
          description: Movie data
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Movie'
        responses:
          '201':
            description: Movie created successfully
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Movie'
          '400':
            description: Bad request
            content:
              application/json:
                example:
                  error: Bad request
          '500':
            description: Internal server error
            content:
              application/json:
                example:
                  error: Internal server error
    /movie/{id}:
      put:
        summary: Update a movie
        description: Updates an existing movie entry.
        operationId: updateMovie
        parameters:
          - name: id
            in: path
            description: ID of the movie to update
            required: true
            schema:
              type: integer
        requestBody:
          description: Updated movie data
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Movie'
        responses:
          '200':
            description: Movie updated successfully
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Movie'
          '400':
            description: Bad request
            content:
              application/json:
                example:
                  error: Bad request
          '404':
            description: Movie not found
            content:
              application/json:
                example:
                  error: Movie not found
          '500':
            description: Internal server error
            content:
              application/json:
                example:
                  error: Internal server error
      delete:
        summary: Delete a movie
        description: Deletes an existing movie entry.
        operationId: deleteMovie
        parameters:
          - name: id
            in: path
            description: ID of the movie to delete
            required: true
            schema:
              type: integer
        responses:
          '200':
            description: Movie deleted successfully
            content:
              application/json:
                example:
                  message: Movie deleted
          '400':
            description: Bad request
            content:
              application/json:
                example:
                  error: Bad request
          '404':
            description: Movie not found
            content:
              application/json:
                example:
                  error: Movie not found
          '500':
            description: Internal server error
            content:
              application/json:
                example:
                  error: Internal server error
